// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/vipex.cc/public/v1/v1.proto/apiResult.proto

package v1_proto // import "codeup.aliyun.com/vipex/go-grpc/api/vipex.cc/public/v1/v1.proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_apiResult_81594a1fa1c15e55, []int{0}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Result) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ErrorDes struct {
	UserMsg              string   `protobuf:"bytes,1,opt,name=userMsg,proto3" json:"userMsg"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDes) Reset()         { *m = ErrorDes{} }
func (m *ErrorDes) String() string { return proto.CompactTextString(m) }
func (*ErrorDes) ProtoMessage()    {}
func (*ErrorDes) Descriptor() ([]byte, []int) {
	return fileDescriptor_apiResult_81594a1fa1c15e55, []int{1}
}
func (m *ErrorDes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDes.Unmarshal(m, b)
}
func (m *ErrorDes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDes.Marshal(b, m, deterministic)
}
func (dst *ErrorDes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDes.Merge(dst, src)
}
func (m *ErrorDes) XXX_Size() int {
	return xxx_messageInfo_ErrorDes.Size(m)
}
func (m *ErrorDes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDes proto.InternalMessageInfo

func (m *ErrorDes) GetUserMsg() string {
	if m != nil {
		return m.UserMsg
	}
	return ""
}

func (m *ErrorDes) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "v1.proto.Result")
	proto.RegisterType((*ErrorDes)(nil), "v1.proto.ErrorDes")
}

func init() {
	proto.RegisterFile("api/vipex.cc/public/v1/v1.proto/apiResult.proto", fileDescriptor_apiResult_81594a1fa1c15e55)
}

var fileDescriptor_apiResult_81594a1fa1c15e55 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x85, 0x89, 0x60, 0xad, 0x19, 0x3b, 0x48, 0xc7, 0xd2, 0xa9, 0x8b, 0x0d, 0xc5, 0x4d, 0x41,
	0xa4, 0xea, 0xe8, 0xd2, 0xd1, 0x45, 0x6c, 0x7a, 0x84, 0x40, 0xe5, 0xc2, 0xa5, 0x0d, 0xfe, 0x7c,
	0x69, 0x6a, 0x70, 0x74, 0xba, 0xfb, 0xf8, 0xde, 0x83, 0x3b, 0x2e, 0x9e, 0x46, 0x0b, 0xa7, 0x0d,
	0xbc, 0x4b, 0x29, 0x85, 0x19, 0xdb, 0x5e, 0x4b, 0xe1, 0x2a, 0xe1, 0xaa, 0xd2, 0x10, 0x0e, 0x38,
	0xf9, 0x06, 0xec, 0xd8, 0x0f, 0x33, 0x27, 0x71, 0x30, 0xf9, 0x9e, 0x47, 0xb3, 0x49, 0x52, 0xbe,
	0x02, 0xa2, 0x33, 0x76, 0x90, 0xb2, 0x8c, 0x15, 0xcb, 0x26, 0x60, 0xb2, 0xe1, 0x11, 0x10, 0xdd,
	0xac, 0x4a, 0x17, 0x19, 0x2b, 0xd6, 0xcd, 0x97, 0xf2, 0x23, 0x8f, 0xaf, 0x44, 0x48, 0x17, 0xb0,
	0x53, 0x7b, 0xb4, 0xe0, 0x43, 0xcc, 0x87, 0x02, 0x4e, 0x46, 0x62, 0x07, 0xbf, 0x7a, 0xc0, 0xba,
	0xbe, 0x9f, 0x94, 0x1e, 0x00, 0x4a, 0x89, 0xaf, 0xf9, 0x7c, 0xa1, 0x70, 0xab, 0xc8, 0xc8, 0x7f,
	0x0f, 0x1d, 0x5c, 0xf5, 0xf0, 0x4b, 0x1b, 0xf9, 0xb1, 0xfb, 0x04, 0x00, 0x00, 0xff, 0xff, 0x09,
	0x44, 0xbd, 0xdf, 0x03, 0x01, 0x00, 0x00,
}
