// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/vipex.cc/aliOss/v1/v1.proto/oss.proto

package v1_proto // import "gitee.com/vipex/go-grpc/api/vipex.cc/aliOss/v1/v1.proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1 "gitee.com/vipex/go-grpc/api/vipex.cc/public/v1/v1.proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OssPutReq struct {
	ReqFile              []byte   `protobuf:"bytes,1,opt,name=reqFile,proto3" json:"reqFile"`
	ObjectKey            string   `protobuf:"bytes,2,opt,name=objectKey,proto3" json:"objectKey"`
	BucketName           string   `protobuf:"bytes,3,opt,name=bucketName,proto3" json:"bucketName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OssPutReq) Reset()         { *m = OssPutReq{} }
func (m *OssPutReq) String() string { return proto.CompactTextString(m) }
func (*OssPutReq) ProtoMessage()    {}
func (*OssPutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oss_19839d7dfafeb6a1, []int{0}
}
func (m *OssPutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OssPutReq.Unmarshal(m, b)
}
func (m *OssPutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OssPutReq.Marshal(b, m, deterministic)
}
func (dst *OssPutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OssPutReq.Merge(dst, src)
}
func (m *OssPutReq) XXX_Size() int {
	return xxx_messageInfo_OssPutReq.Size(m)
}
func (m *OssPutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OssPutReq.DiscardUnknown(m)
}

var xxx_messageInfo_OssPutReq proto.InternalMessageInfo

func (m *OssPutReq) GetReqFile() []byte {
	if m != nil {
		return m.ReqFile
	}
	return nil
}

func (m *OssPutReq) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *OssPutReq) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type OssGetReq struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OssGetReq) Reset()         { *m = OssGetReq{} }
func (m *OssGetReq) String() string { return proto.CompactTextString(m) }
func (*OssGetReq) ProtoMessage()    {}
func (*OssGetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_oss_19839d7dfafeb6a1, []int{1}
}
func (m *OssGetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OssGetReq.Unmarshal(m, b)
}
func (m *OssGetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OssGetReq.Marshal(b, m, deterministic)
}
func (dst *OssGetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OssGetReq.Merge(dst, src)
}
func (m *OssGetReq) XXX_Size() int {
	return xxx_messageInfo_OssGetReq.Size(m)
}
func (m *OssGetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OssGetReq.DiscardUnknown(m)
}

var xxx_messageInfo_OssGetReq proto.InternalMessageInfo

func (m *OssGetReq) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type OssPutRst struct {
	Result               *v1.Result   `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Data                 bool         `protobuf:"varint,2,opt,name=data,proto3" json:"data"`
	ErrorDes             *v1.ErrorDes `protobuf:"bytes,3,opt,name=errorDes,proto3" json:"errorDes"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OssPutRst) Reset()         { *m = OssPutRst{} }
func (m *OssPutRst) String() string { return proto.CompactTextString(m) }
func (*OssPutRst) ProtoMessage()    {}
func (*OssPutRst) Descriptor() ([]byte, []int) {
	return fileDescriptor_oss_19839d7dfafeb6a1, []int{2}
}
func (m *OssPutRst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OssPutRst.Unmarshal(m, b)
}
func (m *OssPutRst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OssPutRst.Marshal(b, m, deterministic)
}
func (dst *OssPutRst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OssPutRst.Merge(dst, src)
}
func (m *OssPutRst) XXX_Size() int {
	return xxx_messageInfo_OssPutRst.Size(m)
}
func (m *OssPutRst) XXX_DiscardUnknown() {
	xxx_messageInfo_OssPutRst.DiscardUnknown(m)
}

var xxx_messageInfo_OssPutRst proto.InternalMessageInfo

func (m *OssPutRst) GetResult() *v1.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OssPutRst) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

func (m *OssPutRst) GetErrorDes() *v1.ErrorDes {
	if m != nil {
		return m.ErrorDes
	}
	return nil
}

type OssResult struct {
	Result               *v1.Result   `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Url                  []string     `protobuf:"bytes,2,rep,name=url,proto3" json:"url"`
	ErrorDes             *v1.ErrorDes `protobuf:"bytes,3,opt,name=errorDes,proto3" json:"errorDes"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OssResult) Reset()         { *m = OssResult{} }
func (m *OssResult) String() string { return proto.CompactTextString(m) }
func (*OssResult) ProtoMessage()    {}
func (*OssResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_oss_19839d7dfafeb6a1, []int{3}
}
func (m *OssResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OssResult.Unmarshal(m, b)
}
func (m *OssResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OssResult.Marshal(b, m, deterministic)
}
func (dst *OssResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OssResult.Merge(dst, src)
}
func (m *OssResult) XXX_Size() int {
	return xxx_messageInfo_OssResult.Size(m)
}
func (m *OssResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OssResult.DiscardUnknown(m)
}

var xxx_messageInfo_OssResult proto.InternalMessageInfo

func (m *OssResult) GetResult() *v1.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OssResult) GetUrl() []string {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *OssResult) GetErrorDes() *v1.ErrorDes {
	if m != nil {
		return m.ErrorDes
	}
	return nil
}

type Oss struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Oss) Reset()         { *m = Oss{} }
func (m *Oss) String() string { return proto.CompactTextString(m) }
func (*Oss) ProtoMessage()    {}
func (*Oss) Descriptor() ([]byte, []int) {
	return fileDescriptor_oss_19839d7dfafeb6a1, []int{4}
}
func (m *Oss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oss.Unmarshal(m, b)
}
func (m *Oss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oss.Marshal(b, m, deterministic)
}
func (dst *Oss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oss.Merge(dst, src)
}
func (m *Oss) XXX_Size() int {
	return xxx_messageInfo_Oss.Size(m)
}
func (m *Oss) XXX_DiscardUnknown() {
	xxx_messageInfo_Oss.DiscardUnknown(m)
}

var xxx_messageInfo_Oss proto.InternalMessageInfo

func (m *Oss) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*OssPutReq)(nil), "v1.proto.OssPutReq")
	proto.RegisterType((*OssGetReq)(nil), "v1.proto.OssGetReq")
	proto.RegisterType((*OssPutRst)(nil), "v1.proto.OssPutRst")
	proto.RegisterType((*OssResult)(nil), "v1.proto.OssResult")
	proto.RegisterType((*Oss)(nil), "v1.proto.Oss")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OssGrpcClient is the client API for OssGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OssGrpcClient interface {
	Put(ctx context.Context, in *OssPutReq, opts ...grpc.CallOption) (*OssPutRst, error)
	Get(ctx context.Context, in *OssGetReq, opts ...grpc.CallOption) (*OssResult, error)
}

type ossGrpcClient struct {
	cc *grpc.ClientConn
}

func NewOssGrpcClient(cc *grpc.ClientConn) OssGrpcClient {
	return &ossGrpcClient{cc}
}

func (c *ossGrpcClient) Put(ctx context.Context, in *OssPutReq, opts ...grpc.CallOption) (*OssPutRst, error) {
	out := new(OssPutRst)
	err := c.cc.Invoke(ctx, "/v1.proto.OssGrpc/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ossGrpcClient) Get(ctx context.Context, in *OssGetReq, opts ...grpc.CallOption) (*OssResult, error) {
	out := new(OssResult)
	err := c.cc.Invoke(ctx, "/v1.proto.OssGrpc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OssGrpcServer is the server API for OssGrpc service.
type OssGrpcServer interface {
	Put(context.Context, *OssPutReq) (*OssPutRst, error)
	Get(context.Context, *OssGetReq) (*OssResult, error)
}

func RegisterOssGrpcServer(s *grpc.Server, srv OssGrpcServer) {
	s.RegisterService(&_OssGrpc_serviceDesc, srv)
}

func _OssGrpc_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssPutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssGrpcServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.proto.OssGrpc/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssGrpcServer).Put(ctx, req.(*OssPutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OssGrpc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OssGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssGrpcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.proto.OssGrpc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssGrpcServer).Get(ctx, req.(*OssGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _OssGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.proto.OssGrpc",
	HandlerType: (*OssGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _OssGrpc_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _OssGrpc_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/vipex.cc/aliOss/v1/v1.proto/oss.proto",
}

func init() {
	proto.RegisterFile("api/vipex.cc/aliOss/v1/v1.proto/oss.proto", fileDescriptor_oss_19839d7dfafeb6a1)
}

var fileDescriptor_oss_19839d7dfafeb6a1 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4f, 0xfa, 0x30,
	0x14, 0x66, 0xec, 0x17, 0x60, 0xe5, 0x77, 0x20, 0xf5, 0xe0, 0x42, 0x8c, 0x21, 0x3b, 0xcd, 0x18,
	0xd7, 0x0c, 0x8f, 0x5e, 0x0c, 0x51, 0x39, 0x98, 0x08, 0xe9, 0xd1, 0x8b, 0xd9, 0xea, 0x0b, 0xa9,
	0x8e, 0xb4, 0xb4, 0xdd, 0x94, 0xff, 0xde, 0xac, 0x65, 0x20, 0x70, 0x30, 0x9c, 0xfa, 0xf5, 0xbd,
	0xf7, 0xbd, 0xef, 0x7b, 0xed, 0x43, 0x57, 0x99, 0xe4, 0xa4, 0xe2, 0x12, 0xbe, 0x13, 0xc6, 0x48,
	0x56, 0xf0, 0x99, 0xd6, 0xa4, 0x4a, 0x49, 0x95, 0x26, 0x52, 0x09, 0x23, 0x88, 0xd0, 0xda, 0x21,
	0xdc, 0x6b, 0x62, 0x43, 0xb2, 0x47, 0x92, 0x65, 0x5e, 0x70, 0xb6, 0x47, 0xca, 0x24, 0xa7, 0xa0,
	0xcb, 0xc2, 0xb8, 0x7b, 0xc4, 0x50, 0x30, 0xd3, 0x7a, 0x5e, 0x1a, 0x0a, 0x2b, 0x1c, 0xa2, 0xae,
	0x82, 0xd5, 0x13, 0x2f, 0x20, 0xf4, 0x46, 0x5e, 0xfc, 0x9f, 0x36, 0x57, 0x7c, 0x81, 0x02, 0x91,
	0x7f, 0x00, 0x33, 0xcf, 0xb0, 0x0e, 0xdb, 0x23, 0x2f, 0x0e, 0xe8, 0x2e, 0x80, 0x2f, 0x11, 0xca,
	0x4b, 0xf6, 0x09, 0xe6, 0x25, 0x5b, 0x42, 0xe8, 0xdb, 0xf4, 0xaf, 0x48, 0x74, 0x6d, 0x45, 0xa6,
	0x60, 0x45, 0xf6, 0x8b, 0xbd, 0xa3, 0xe2, 0xf5, 0xd6, 0x91, 0x36, 0x38, 0x46, 0x1d, 0x65, 0xed,
	0xda, 0xc2, 0xfe, 0x78, 0x90, 0x34, 0x93, 0x24, 0x6e, 0x0c, 0xba, 0xc9, 0x63, 0x8c, 0xfe, 0xbd,
	0x67, 0x26, 0xb3, 0xe6, 0x7a, 0xd4, 0x62, 0x9c, 0xa0, 0x1e, 0x28, 0x25, 0xd4, 0x03, 0x68, 0xeb,
	0xaa, 0x3f, 0xc6, 0x3b, 0xfe, 0xe3, 0x26, 0x43, 0xb7, 0x35, 0xd1, 0x97, 0x95, 0x76, 0x8d, 0x4f,
	0x90, 0x1e, 0x20, 0xbf, 0x54, 0x45, 0xd8, 0x1e, 0xf9, 0x71, 0x40, 0x6b, 0x78, 0xb2, 0xf0, 0x39,
	0xf2, 0x67, 0x5a, 0x37, 0x8d, 0xdc, 0x9b, 0xd4, 0x70, 0x2c, 0x50, 0xb7, 0x7e, 0x39, 0x25, 0x19,
	0x4e, 0x91, 0x3f, 0x2f, 0x0d, 0x3e, 0xdb, 0x35, 0xda, 0x7e, 0xdc, 0xf0, 0x38, 0xa8, 0x4d, 0xd4,
	0xaa, 0x29, 0x53, 0x38, 0xa4, 0xb8, 0x6f, 0x38, 0xa0, 0xb8, 0x89, 0xa2, 0xd6, 0x64, 0xf2, 0x7a,
	0xbf, 0xe0, 0x06, 0x20, 0x61, 0x62, 0xe9, 0x16, 0x89, 0x2c, 0xc4, 0xcd, 0x42, 0x49, 0x46, 0xfe,
	0xd8, 0xc7, 0xbb, 0x2a, 0x7d, 0xb3, 0x20, 0xef, 0xd8, 0xe3, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x26, 0x10, 0xba, 0xc2, 0x02, 0x00, 0x00,
}
