// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb // import "gitee.com/vipex/go-grpc/api/vipex.cc/oauth2/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5737d3af2bb825d1, []int{0}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Result) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ErrorDes struct {
	UserMsg              string   `protobuf:"bytes,1,opt,name=userMsg,proto3" json:"userMsg"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorDes) Reset()         { *m = ErrorDes{} }
func (m *ErrorDes) String() string { return proto.CompactTextString(m) }
func (*ErrorDes) ProtoMessage()    {}
func (*ErrorDes) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5737d3af2bb825d1, []int{1}
}
func (m *ErrorDes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDes.Unmarshal(m, b)
}
func (m *ErrorDes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDes.Marshal(b, m, deterministic)
}
func (dst *ErrorDes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDes.Merge(dst, src)
}
func (m *ErrorDes) XXX_Size() int {
	return xxx_messageInfo_ErrorDes.Size(m)
}
func (m *ErrorDes) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDes.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDes proto.InternalMessageInfo

func (m *ErrorDes) GetUserMsg() string {
	if m != nil {
		return m.UserMsg
	}
	return ""
}

func (m *ErrorDes) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type BaseResult struct {
	Result               *Result   `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Data                 bool      `protobuf:"varint,2,opt,name=data,proto3" json:"data"`
	ErrorDes             *ErrorDes `protobuf:"bytes,3,opt,name=errorDes,proto3" json:"errorDes"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BaseResult) Reset()         { *m = BaseResult{} }
func (m *BaseResult) String() string { return proto.CompactTextString(m) }
func (*BaseResult) ProtoMessage()    {}
func (*BaseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5737d3af2bb825d1, []int{2}
}
func (m *BaseResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResult.Unmarshal(m, b)
}
func (m *BaseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResult.Marshal(b, m, deterministic)
}
func (dst *BaseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResult.Merge(dst, src)
}
func (m *BaseResult) XXX_Size() int {
	return xxx_messageInfo_BaseResult.Size(m)
}
func (m *BaseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResult.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResult proto.InternalMessageInfo

func (m *BaseResult) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *BaseResult) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

func (m *BaseResult) GetErrorDes() *ErrorDes {
	if m != nil {
		return m.ErrorDes
	}
	return nil
}

type User struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	Pswd                 string   `protobuf:"bytes,2,opt,name=pswd,proto3" json:"pswd"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_5737d3af2bb825d1, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *User) GetPswd() string {
	if m != nil {
		return m.Pswd
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*ErrorDes)(nil), "pb.ErrorDes")
	proto.RegisterType((*BaseResult)(nil), "pb.BaseResult")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_5737d3af2bb825d1) }

var fileDescriptor_user_5737d3af2bb825d1 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x51, 0xbf, 0x4f, 0xf3, 0x30,
	0x10, 0xfd, 0xd2, 0xaf, 0x0d, 0xe1, 0x40, 0x0c, 0x1e, 0x50, 0xc4, 0x54, 0x99, 0x25, 0x0b, 0xb6,
	0x14, 0x10, 0x03, 0x48, 0x0c, 0x05, 0xc4, 0x02, 0x8b, 0x25, 0x16, 0xb6, 0xc4, 0x39, 0x85, 0x48,
	0x50, 0x5b, 0xe7, 0x04, 0xf8, 0xf3, 0xd1, 0xb9, 0x0e, 0xdd, 0xde, 0xbb, 0xf7, 0x23, 0x2f, 0x32,
	0xc0, 0x14, 0x90, 0x94, 0x27, 0x37, 0x3a, 0xb1, 0xf0, 0xad, 0xbc, 0x81, 0xdc, 0x60, 0x98, 0x3e,
	0x46, 0x51, 0xc2, 0x01, 0x12, 0xdd, 0xbb, 0x0e, 0xcb, 0x6c, 0x9d, 0x55, 0x2b, 0x33, 0x53, 0x71,
	0x0a, 0x39, 0x12, 0xbd, 0x84, 0xbe, 0x5c, 0xac, 0xb3, 0xea, 0xd0, 0x24, 0x26, 0xef, 0xa0, 0x78,
	0x24, 0x72, 0xf4, 0x80, 0x81, 0xd3, 0xdc, 0xcc, 0xa6, 0x2c, 0x9a, 0x66, 0xca, 0x8a, 0x75, 0x1d,
	0xee, 0xe3, 0x33, 0x95, 0x5b, 0x80, 0x4d, 0x13, 0x30, 0x7d, 0x5f, 0x42, 0x4e, 0x11, 0xc5, 0x82,
	0xa3, 0x1a, 0x94, 0x6f, 0xd5, 0x4e, 0x33, 0x49, 0x11, 0x02, 0x96, 0x5d, 0x33, 0x36, 0xb1, 0xa8,
	0x30, 0x11, 0x8b, 0x0a, 0x0a, 0x4c, 0x2b, 0xca, 0xff, 0x31, 0x79, 0xcc, 0xc9, 0x79, 0x99, 0xf9,
	0x53, 0xa5, 0x82, 0xe5, 0x6b, 0x40, 0xe2, 0x16, 0x1e, 0x97, 0x86, 0x46, 0xcc, 0x37, 0x1f, 0xbe,
	0xbb, 0x34, 0x31, 0xe2, 0x5a, 0x43, 0xc1, 0xfe, 0x27, 0xf2, 0x56, 0x9c, 0xc3, 0xea, 0xd9, 0xf5,
	0xc3, 0x56, 0x14, 0x5c, 0xce, 0xe7, 0xb3, 0x13, 0x46, 0xfb, 0x1f, 0x90, 0xff, 0x36, 0xd7, 0x6f,
	0x57, 0xfd, 0x30, 0x22, 0x2a, 0xeb, 0x3e, 0xf5, 0xd7, 0xe0, 0xf1, 0x47, 0xf7, 0xee, 0xa2, 0x27,
	0x6f, 0x75, 0xe3, 0x87, 0xdd, 0x45, 0x59, 0xab, 0x5d, 0x33, 0x8d, 0xef, 0xb5, 0x8e, 0xaf, 0x70,
	0xeb, 0xdb, 0x36, 0x8f, 0xe8, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xc6, 0x72, 0x08, 0x9d,
	0x01, 0x00, 0x00,
}
