// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/vipex.cc/oauth2/proto/user.proto

package pb // import "codeup.aliyun.com/vipex/go-grpc/api/vipex.cc/oauth2/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pub "codeup.aliyun.com/vipex/go-grpc/api/vipex.cc/public/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserResult struct {
	Result               *pub.Result   `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	Data                 bool             `protobuf:"varint,2,opt,name=data,proto3" json:"data"`
	ErrorDes             *pub.ErrorDes `protobuf:"bytes,3,opt,name=errorDes,proto3" json:"errorDes"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserResult) Reset()         { *m = UserResult{} }
func (m *UserResult) String() string { return proto.CompactTextString(m) }
func (*UserResult) ProtoMessage()    {}
func (*UserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_7a6cb3a40510de2f, []int{0}
}
func (m *UserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResult.Unmarshal(m, b)
}
func (m *UserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResult.Marshal(b, m, deterministic)
}
func (dst *UserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResult.Merge(dst, src)
}
func (m *UserResult) XXX_Size() int {
	return xxx_messageInfo_UserResult.Size(m)
}
func (m *UserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResult.DiscardUnknown(m)
}

var xxx_messageInfo_UserResult proto.InternalMessageInfo

func (m *UserResult) GetResult() *pub.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UserResult) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

func (m *UserResult) GetErrorDes() *pub.ErrorDes {
	if m != nil {
		return m.ErrorDes
	}
	return nil
}

type User struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	Pswd                 string   `protobuf:"bytes,2,opt,name=pswd,proto3" json:"pswd"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_7a6cb3a40510de2f, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *User) GetPswd() string {
	if m != nil {
		return m.Pswd
	}
	return ""
}

func init() {
	proto.RegisterType((*UserResult)(nil), "pb.UserResult")
	proto.RegisterType((*User)(nil), "pb.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserGrpcClient is the client API for UserGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserGrpcClient interface {
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResult, error)
}

type userGrpcClient struct {
	cc *grpc.ClientConn
}

func NewUserGrpcClient(cc *grpc.ClientConn) UserGrpcClient {
	return &userGrpcClient{cc}
}

func (c *userGrpcClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResult, error) {
	out := new(UserResult)
	err := c.cc.Invoke(ctx, "/pb.UserGrpc/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGrpcServer is the server API for UserGrpc service.
type UserGrpcServer interface {
	Login(context.Context, *User) (*UserResult, error)
}

func RegisterUserGrpcServer(s *grpc.Server, srv UserGrpcServer) {
	s.RegisterService(&_UserGrpc_serviceDesc, srv)
}

func _UserGrpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGrpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserGrpc/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGrpcServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserGrpc",
	HandlerType: (*UserGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserGrpc_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/vipex.cc/oauth2/proto/user.proto",
}

func init() {
	proto.RegisterFile("api/vipex.cc/oauth2/proto/user.proto", fileDescriptor_user_7a6cb3a40510de2f)
}

var fileDescriptor_user_7a6cb3a40510de2f = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0xdd, 0xf3, 0x3c, 0xf6, 0x46, 0xb1, 0x48, 0xb5, 0x5c, 0x75, 0xac, 0x16, 0x6b, 0x61,
	0x02, 0xab, 0xd8, 0xd8, 0x89, 0x62, 0x63, 0x15, 0xb0, 0xb1, 0x4b, 0x72, 0x61, 0x0d, 0x9c, 0x9b,
	0x21, 0xc9, 0xaa, 0x3f, 0x5f, 0x32, 0x59, 0x05, 0x8b, 0xeb, 0x3e, 0xde, 0x7b, 0xf3, 0x66, 0x18,
	0xb8, 0x54, 0xe8, 0xc4, 0xa7, 0x43, 0xfb, 0xcd, 0x8d, 0x11, 0x5e, 0x4d, 0xe9, 0xbd, 0x17, 0x18,
	0x7c, 0xf2, 0x62, 0x8a, 0x36, 0x70, 0x42, 0xb6, 0x40, 0xbd, 0xb9, 0xfa, 0x97, 0xc4, 0x49, 0xef,
	0x9d, 0x99, 0x93, 0x0a, 0x9d, 0xb4, 0x71, 0xda, 0xa7, 0x12, 0x6f, 0x47, 0x80, 0xd7, 0x68, 0x43,
	0xd1, 0x58, 0x0b, 0xab, 0x40, 0xd4, 0x54, 0xdb, 0xaa, 0x3b, 0xed, 0x81, 0xa3, 0xe6, 0xc5, 0x93,
	0xb3, 0xc3, 0x18, 0x2c, 0x77, 0x2a, 0xa9, 0x66, 0xb1, 0xad, 0xba, 0x5a, 0x12, 0xb3, 0x0e, 0x6a,
	0x1b, 0x82, 0x0f, 0x8f, 0x36, 0x36, 0xc7, 0x34, 0x79, 0x96, 0x27, 0x9f, 0x66, 0x4d, 0xfe, 0xb9,
	0x2d, 0x87, 0x65, 0xde, 0x97, 0x5b, 0xf2, 0xd1, 0xb4, 0x67, 0x2d, 0x89, 0xb3, 0x86, 0xf1, 0x6b,
	0x47, 0xcd, 0x6b, 0x49, 0xdc, 0x0b, 0xa8, 0x73, 0xfe, 0x39, 0xa0, 0x61, 0x17, 0x70, 0xf2, 0xe2,
	0x07, 0x37, 0xb2, 0x3a, 0x97, 0x67, 0x79, 0x73, 0xfe, 0x4b, 0xe5, 0xc8, 0xf6, 0xe8, 0xe1, 0xee,
	0xed, 0x76, 0x70, 0xc9, 0x5a, 0x6e, 0xfc, 0x47, 0xf9, 0x81, 0x18, 0xfc, 0xf5, 0x10, 0xd0, 0x88,
	0x83, 0xff, 0xbb, 0x47, 0xad, 0x57, 0x44, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x72,
	0x4f, 0x0f, 0x66, 0x01, 0x00, 0x00,
}
