// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/vipex.cc/public/v1/v1.proto/apiResult.proto

package v1_interface

import v1_proto "gitee.com/vipex/go-grpc/api/vipex.cc/public/v1/v1.proto"

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
